stages:
  # preprocess:
  #   cmd: python source/preprocess.py
  #   deps:
  #   - source/preprocess.py
  #   - source/network/dataset.py
  #   - data/raw/
  #   params:
  #   - preprocess.input_directory
  #   - preprocess.dry_output_directory
  #   - preprocess.short_output_directory
  #   - preprocess.wet_output_directory
  #   - preprocess.board_chunk_size
  #   - preprocess.sliding_mean_length
  #   - preprocess.noise_duration
  #   - preprocess.num_noises
  #   - preprocess.plate_reverb_path
  #   - preprocess.model_batch_size
  #   - train.input_size
  #   - general.sample_rate
  #   outs:
  #   - data/processed/
  train:
    cmd: python3 source/train.py
    deps:
    - source/train.py
    - source/network/
    - source/network/dataset.py
    - source/network/metrics.py
    - source/network/training.py
    - source/network/testing.py
    - source/network/ravepqmf.py
    - source/network/tcn.py
    - source/network/CombinedModels.py
    - source/network/tcnblocktraining.py
    - source/network/latent.py
    - source/network/discriminator.py
    - data/processed/
    params:
    - general.random_seed
    - general.sample_rate
    - general.input_size
    - train.input_file
    - train.name
    - train.device_request
    - train.n_inputs
    - train.n_bands
    - train.latent_dim
    - train.epochs
    - train.batch_size
    - train.kernel_size
    - train.n_blocks
    - train.dilation_growth
    - train.n_channels
    - train.lr
    - train.use_kl
    - train.use_skip
    - train.scheduler_rate
    - train.use_tcn
    - train.use_spectral
    - train.use_pqmf
    - train.use_adversarial
  #   outs:
  #   - model/checkpoints/
  # export:
  #   cmd: python3 source/export.py
  #   deps:
  #   - source/export.py
  #   - model/checkpoints/
  #   params:
  #   - general.input_size
  #   - train.train_mode
  #   outs:
  #   - model/exports/
  save_logs:
    cmd: python3 source/utils/logs.py
    outs:
    - exp_logs/slurm
    - exp_logs/tensorboard
