general:
  sample_rate: 44100
  random_seed: 55
  input_size: 508032
train:
  input_file: data/processed/preprocessed_data.pt
  name: model
  scheduler_rate: 0.1
  device_request: cuda
  n_inputs: 1
  n_bands: 8
  latent_dim: 64
  epochs: 750
  batch_size: 2
  kernel_size: 17
  n_blocks: 2
  dilation_growth: 15
  n_channels: 32
  lr: 0.0001
  use_kl: false
  use_skip: true
  use_tcn: false
  use_pqmf: true
  use_adversarial: false
  use_noise: true
metrics:
  loss_function: combined    # Options: 'mse', 'spectral_distance', 'single_stft_loss', 'fft_loss'
  additional_mse: true
  additional_spec: true
  additional_stft: true
  additional_fft: true
discriminator:
  lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  n_layers: 4
  n_channels: 64
  kernel_size: 4
  stride: 2
  padding: 1
gan:
  loss_type: hinge    # Options: 'hinge', 'square'
