general:
  sample_rate: 44100
  random_seed: 55
  input_size: 508032
train:
  input_file: data/processed/preprocessed_data.pt
  name: model
  scheduler_rate: 1
  device_request: 'cuda'
  n_inputs: 1
  n_bands: 1
  latent_dim: 64
  epochs: 500
  batch_size: 2
  kernel_size: 7
  n_blocks: 5
  dilation_growth: 3
  n_channels: 128
  lr: 0.0001
  use_kl: false
  use_skip: true
  use_tcn: false
  use_spectral: false
  use_pqmf: true
  use_adversarial: true
