general:
  sample_rate: 44100
  random_seed: 55
  input_size: 508032
# preprocess:
#   board_chunk_size: 1024
#   sliding_mean_length: 200
#   noise_duration: 5
#   num_noises: 100
#   plate_reverb_path: C:\Program Files\Common Files\VST3\Rev PLATE-140.vst3
#   input_directory: C:\Users\maxim\Documents\TUBerlin\TCN-VAE-pipeline\data\raw
#   dry_output_directory: C:\Users\maxim\Documents\TUBerlin\TCN-VAE-pipeline\data\dry
#   short_output_directory: C:\Users\maxim\Documents\TUBerlin\TCN-VAE-pipeline\data\short
#   wet_output_directory: C:\Users\maxim\Documents\TUBserlin\TCN-VAE-pipeline\data\wet
#   model_batch_size: 32
train:
  input_file: data/processed/preprocessed_data.pt
  name: model
  scheduler_rate: 0.1
  device_request: 'cuda'
  n_inputs: 1
  n_bands: 1
  latent_dim: 128
  epochs: 1
  batch_size: 2
  kernel_size: 13
  n_blocks: 4
  dilation_growth: 10
  n_channels: 32
  lr: 0.001
  use_kl: false
  use_skip: true
  use_tcn: false
  use_spectral: true
  use_pqmf: true

