general:
  sample_rate: 44100
  random_seed: 55
  input_size: 508032
train:
  input_file: data/processed/preprocessed_data.pt
  name: model
  scheduler_rate: 0.1
  device_request: 'cuda'
  n_inputs: 1
  n_bands: 2
  latent_dim: 64
  epochs: 7
  batch_size: 2
  kernel_size: 17
  n_blocks: 3
  dilation_growth: 15
  stride: 1
  dilate_conv: true
  n_channels: 32
  lr: 0.0001
  use_kl: false
  use_skip: true
  use_latent: 'None' # Options: 'dense', 'conv', "None"
  use_tcn: false
  use_pqmf: true
  use_adversarial: false
  use_noise: false
  use_wn: true
  use_batch_norm: true
  use_residual: true
  activation: 'prelu' # Options: 'prelu', 'leaky_relu'
metrics:
  loss_function: 'combined'  # Options: 'mse', 'spectral_distance', 'single_stft_loss', 'fft_loss', 'combined'
  combined_spectral_weight: 0.01
  combined_mse_weight: 100
  additional_mse: true
  additional_spec: true
  additional_stft: true
  additional_fft: true
discriminator:
  lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  n_layers: 1
  n_channels: 64
  kernel_size: 4
  stride: 2
  padding: 1
gan:
  loss_type: 'hinge'  # Options: 'hinge', 'square'
